/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedPostsNewRouteImport } from './routes/_authed/posts/new'
import { Route as AuthedPlacesNewRouteImport } from './routes/_authed/places/new'
import { Route as AdminAdminDefaultPlacesRouteImport } from './routes/_admin/admin/default-places'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsNewRoute = AuthedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacesNewRoute = AuthedPlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminAdminDefaultPlacesRoute = AdminAdminDefaultPlacesRouteImport.update({
  id: '/admin/default-places',
  path: '/admin/default-places',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/home': typeof AuthedHomeRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/default-places': typeof AdminAdminDefaultPlacesRoute
  '/places/new': typeof AuthedPlacesNewRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/home': typeof AuthedHomeRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/default-places': typeof AdminAdminDefaultPlacesRoute
  '/places/new': typeof AuthedPlacesNewRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/_admin/admin/default-places': typeof AdminAdminDefaultPlacesRoute
  '/_authed/places/new': typeof AuthedPlacesNewRoute
  '/_authed/posts/new': typeof AuthedPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/home'
    | '/domain/$domain'
    | '/p/$slug'
    | '/posts/$postId'
    | '/admin/default-places'
    | '/places/new'
    | '/posts/new'
    | '/api/auth/$'
    | '/admin'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/home'
    | '/domain/$domain'
    | '/p/$slug'
    | '/posts/$postId'
    | '/admin/default-places'
    | '/places/new'
    | '/posts/new'
    | '/api/auth/$'
    | '/admin'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/home'
    | '/domain/$domain'
    | '/p/$slug'
    | '/posts/$postId'
    | '/_admin/admin/default-places'
    | '/_authed/places/new'
    | '/_authed/posts/new'
    | '/api/auth/$'
    | '/_admin/admin/'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DomainDomainRoute: typeof DomainDomainRoute
  PSlugRoute: typeof PSlugRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts/new': {
      id: '/_authed/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthedPostsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/places/new': {
      id: '/_authed/places/new'
      path: '/places/new'
      fullPath: '/places/new'
      preLoaderRoute: typeof AuthedPlacesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_admin/admin/default-places': {
      id: '/_admin/admin/default-places'
      path: '/admin/default-places'
      fullPath: '/admin/default-places'
      preLoaderRoute: typeof AdminAdminDefaultPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDefaultPlacesRoute: typeof AdminAdminDefaultPlacesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDefaultPlacesRoute: AdminAdminDefaultPlacesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedPlacesNewRoute: typeof AuthedPlacesNewRoute
  AuthedPostsNewRoute: typeof AuthedPostsNewRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedPlacesNewRoute: AuthedPlacesNewRoute,
  AuthedPostsNewRoute: AuthedPostsNewRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DomainDomainRoute: DomainDomainRoute,
  PSlugRoute: PSlugRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
